steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/a5reactapp/a5reactapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/a5reactapp/a5reactapp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'a5reactapp', '--image', 'gcr.io/a5reactapp/a5reactapp', '--region', 'us-central1', '--platform', 'managed','--port','3000']
images:
- gcr.io/a5reactapp/a5reactapp